version: "3"

volumes:
  postgres_volume:
  redis-data:

services:
  pg-auth-service:
    image: postgres:14-alpine3.17
    container_name: pg-auth-service
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./server/auth-service/.env

  migrator-auth-service:
    build:
      context: ./server/auth-service
      dockerfile: migrator.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-auth-service

  redis-auth-service:
    image: redis:7.2.5-alpine3.20
    container_name: redis-auth-service
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data