version: "3"

volumes:
  postgres_volume:

services:
  pg-auth-service:
    image: postgres:14-alpine3.17
    container_name: pg-auth-service
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./server/auth-service/.env

  migrator:
    build:
      context: ./server/auth-service
      dockerfile: migrator.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-auth-service