name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          cache: false

      - name: Run golangci-lint for Auth service
        uses: golangci/golangci-lint-action@v6
        with:
            version: v1.60.3
            args: --config=${{ github.workspace }}/auth-service/.golangci.pipeline.yaml ./...
            working-directory: auth-service

      - name: Run golangci-lint for Auth-api-gateway service
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
          args: --config=${{ github.workspace }}/api-gateway/.golangci.pipeline.yaml ./...
          working-directory: api-gateway

      - name: Run golangci-lint for mail service
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
          args: --config=${{ github.workspace }}/mail-checking-service/.golangci.pipeline.yaml ./...
          working-directory: mail-checking-service