name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          cache: false

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.60.3
          echo "${GOPATH}/bin" >> $GITHUB_PATH

      - name: golangci-lint
        run: |
          cd server/auth-service
          golangci-lint run --timeout=30m --config=.golangci.pipeline.yaml ./...
          env:
          GOLANGCI_LINT_VERSION: v1.60