{
 "title": "My_Dashboard",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debbuging.",
 "tags": [
  "alertmanager",
  "prometheus",
  "alerting"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(alertmanager_build_info)"
   }
  ]
 },
 "panels": [
  {
   "title": "General info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Количество активных сервисов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(up)-1" }
   ]
  },
  {
   "title": "Количество регистраций",
   "type": "stat",
   "description": "Показывает количество успешно зарегестрированных пользователей",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_service_space_grpc_auth_service_registration_total"
    }
   ]
  },
  {
   "title": "Количество верифицированных пользователей",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mail_service_space_grpc_mail_service_success_verification_total"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(auth_service_space_grpc_auth_service_requests_total[15s])\r\n\r\n  ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Количество запросов ",
   "type": "stat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "auth_service_space_grpc_auth_service_requests_total"
    }
   ]
  },
  {
   "title": "Auth Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(auth_service_space_grpc_auth_service_response_time_second_bucket[15s])) by (le, status)) ",
     "legendFormat": "0.9q: {{status}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(auth_service_space_grpc_auth_service_response_time_second_bucket[15s])) by (le, status)) ",
     "legendFormat": "0.5q: {{status}}"
    }
   ]
  },
  {
   "title": "RPS Auth service",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(auth_service_space_grpc_auth_service_requests_total[15s])"
    }
   ]
  },
  {
   "title": "Api Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(api_gateway_space_rest_api_gateway_response_time_second_bucket[15s])) by (le, status)) ",
     "legendFormat": "0.9q: {{status}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(api_gateway_space_rest_api_gateway_response_time_second_bucket[15s])) by (le, status)) ",
     "legendFormat": "0.5q: {{status}}"
    }
   ]
  },
  {
   "title": "RPS api gateway",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(api_gateway_space_rest_api_gateway_requests_total[15s])"
    }
   ]
  },
  { "title": "Mail Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(mail_service_space_grpc_mail_service_response_time_second_bucket[15s])) by (le, status)) ",
     "legendFormat": "0.9q:  {{status}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(mail_service_space_grpc_mail_service_response_time_second_bucket[15s])) by (le, status)) ",
     "legendFormat": "0.5q: {{status}}"
    }
   ]
  },
  {
   "title": "RPS mail service",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mail_service_space_grpc_mail_service_requests_total[15s])"
    }
   ]
  }
 ]
}